export const PIPELINE_ALIAS_DEFINITIONS = Object.freeze({
  "plan-tasks-implement-verify": { phases: "plan,tasks,implement,verify", taskStyle: "option", implementFlags: true },
  "plan-implement-verify": { phases: "plan,implement,verify", taskStyle: "option", implementFlags: true },
  "tasks-implement-verify": { phases: "tasks,implement,verify", taskStyle: "option", implementFlags: true },
  "discuss-plan-tasks-implement": { phases: "discuss,plan,tasks,implement", taskStyle: "option", implementFlags: true },
  "discuss-plan-implement": { phases: "discuss,plan,implement", taskStyle: "option", implementFlags: true },
  "discuss-plan-implement-verify": { phases: "discuss,plan,implement,verify", taskStyle: "option", implementFlags: true },
  "discuss-plan-tasks-implement-verify": { phases: "discuss,plan,tasks,implement,verify", taskStyle: "option", implementFlags: true },
  "plan-verify": { phases: "plan,verify", taskStyle: "positional" },
  "plan-tasks": { phases: "plan,tasks", taskStyle: "positional" },
  "discuss-plan": { phases: "discuss,plan", taskStyle: "positional" },
  "discuss-spec": { phases: "discuss,spec", taskStyle: "positional" },
  "spec-plan": { phases: "spec,plan", taskStyle: "positional" },
  "spec-plan-tasks": { phases: "spec,plan,tasks", taskStyle: "positional" },
  "discuss-spec-plan": { phases: "discuss,spec,plan", taskStyle: "positional" },
  "discuss-spec-plan-tasks": { phases: "discuss,spec,plan,tasks", taskStyle: "positional" },
  "spec-plan-implement": { phases: "spec,plan,implement", taskStyle: "positional", implementFlags: true },
  "spec-plan-tasks-implement": { phases: "spec,plan,tasks,implement", taskStyle: "positional", implementFlags: true },
  "discuss-spec-plan-implement": { phases: "discuss,spec,plan,implement", taskStyle: "positional", implementFlags: true },
  "discuss-spec-plan-tasks-implement": { phases: "discuss,spec,plan,tasks,implement", taskStyle: "positional", implementFlags: true },
  "spec-plan-verify": { phases: "spec,plan,verify", taskStyle: "positional" },
  "spec-plan-tasks-verify": { phases: "spec,plan,tasks,verify", taskStyle: "positional" },
  "discuss-spec-plan-verify": { phases: "discuss,spec,plan,verify", taskStyle: "positional" },
  "discuss-spec-plan-tasks-verify": { phases: "discuss,spec,plan,tasks,verify", taskStyle: "positional" },
  "spec-plan-implement-verify": { phases: "spec,plan,implement,verify", taskStyle: "option", implementFlags: true },
  "spec-plan-tasks-implement-verify": { phases: "spec,plan,tasks,implement,verify", taskStyle: "option", implementFlags: true },
  "discuss-spec-plan-implement-verify": { phases: "discuss,spec,plan,implement,verify", taskStyle: "option", implementFlags: true },
  "discuss-spec-plan-tasks-implement-verify": { phases: "discuss,spec,plan,tasks,implement,verify", taskStyle: "option", implementFlags: true },
  "discuss-plan-tasks": { phases: "discuss,plan,tasks", taskStyle: "positional" },
  "plan-tasks-verify": { phases: "plan,tasks,verify", taskStyle: "positional" },
  "discuss-plan-verify": { phases: "discuss,plan,verify", taskStyle: "positional" },
  "discuss-plan-tasks-verify": { phases: "discuss,plan,tasks,verify", taskStyle: "positional" },
});

export const PIPELINE_ALIAS_COMMANDS = new Set(Object.keys(PIPELINE_ALIAS_DEFINITIONS));
